import type { ProviderCapabilities } from '../types/domain';

export const OPEN_FOOTBALL_CAPABILITIES: ProviderCapabilities = {
  schedules: true,
  scores: true,
  delayedScores: false,
  liveStatus: false,
  standings: false,
  teams: true,
  competitionMetadata: true,
  headToHead: false,
  form: false,
  matchEvents: false,
  lineups: false,
  playerStatistics: false,
  knockoutStages: false,
  teamCrests: false,
  historicalSeasons: true,
  requiresApiKey: false,
  refreshLimits: { requestsPerMinute: null, requestsPerDay: null },
};

export const THE_SPORTS_DB_CAPABILITIES: ProviderCapabilities = {
  schedules: true,
  scores: true,
  delayedScores: true,
  liveStatus: false,
  standings: false,
  teams: false,
  competitionMetadata: false,
  headToHead: false,
  form: false,
  matchEvents: false,
  lineups: false,
  playerStatistics: false,
  knockoutStages: false,
  teamCrests: true,
  historicalSeasons: false,
  requiresApiKey: false,
  refreshLimits: { requestsPerMinute: 30, requestsPerDay: null },
};

export const ESPN_ANALYSIS_CAPABILITIES: ProviderCapabilities = {
  schedules: false,
  scores: false,
  delayedScores: false,
  liveStatus: false,
  standings: false,
  teams: false,
  competitionMetadata: false,
  headToHead: false,
  form: false,
  matchEvents: true,
  lineups: true,
  playerStatistics: true,
  knockoutStages: false,
  teamCrests: true,
  historicalSeasons: false,
  requiresApiKey: false,
  refreshLimits: { requestsPerMinute: null, requestsPerDay: null },
};

export const FOOTBALL_DATA_ORG_CAPABILITIES: ProviderCapabilities = {
  schedules: true,
  scores: true,
  delayedScores: true,
  liveStatus: true,
  standings: true,
  teams: true,
  competitionMetadata: true,
  headToHead: true,
  form: true,
  matchEvents: false,
  lineups: false,
  playerStatistics: false,
  knockoutStages: true,
  teamCrests: true,
  historicalSeasons: true,
  requiresApiKey: true,
  refreshLimits: { requestsPerMinute: 10, requestsPerDay: null },
};

export const API_FOOTBALL_CAPABILITIES: ProviderCapabilities = {
  schedules: true,
  scores: true,
  delayedScores: true,
  liveStatus: true,
  standings: true,
  teams: true,
  competitionMetadata: true,
  headToHead: true,
  form: true,
  matchEvents: true,
  lineups: true,
  playerStatistics: true,
  knockoutStages: true,
  teamCrests: true,
  historicalSeasons: true,
  requiresApiKey: true,
  refreshLimits: { requestsPerMinute: 30, requestsPerDay: 100 },
};

export const CACHED_PROVIDER_CAPABILITIES: ProviderCapabilities = {
  schedules: true,
  scores: true,
  delayedScores: true,
  liveStatus: false,
  standings: true,
  teams: true,
  competitionMetadata: true,
  headToHead: true,
  form: true,
  matchEvents: false,
  lineups: false,
  playerStatistics: false,
  knockoutStages: true,
  teamCrests: true,
  historicalSeasons: true,
  requiresApiKey: false,
  refreshLimits: { requestsPerMinute: null, requestsPerDay: null },
};
